--Q1.  What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customerAnalysis
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from CustomerAnalysis
where discount_applied= 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customerAnalysis)


--Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased, 
    ROUND(CAST(AVG(review_rating) AS NUMERIC(10,2)), 2) AS [Average Product Rating]
FROM 
    CustomerAnalysis
GROUP BY 
    item_purchased
ORDER BY 
    [Average Product Rating] DESC;


--Q4. Compare the average purchase amounts between standard and express shipping
select shipping_type,
AVG(purchase_amount) AS [Average purchase amount]
from CustomerAnalysis
where shipping_type in ('Standard','Express')
group by shipping_type



--Q5. Do subscribed customers spend more? Compare average spend and total revenue
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from CustomerAnalysis
group by subscription_status
order by total_revenue,avg_spend desc;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    item_purchased, 
    
    CAST(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0.0 END) / COUNT(*)) * 100 
    AS DECIMAL(10, 2)) AS discount_rate
FROM 
    CustomerAnalysis
GROUP BY 
    item_purchased
ORDER BY 
    discount_rate DESC;



--Q7. Segment customers into New, Returning and Loyal based on their 
   --total number of previous purchase and show the count of each segment 
 WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases, 
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM CustomerAnalysis
)

SELECT 
    customer_segment, 
    COUNT(*) AS [Number of Customers] 
FROM customer_type
GROUP BY customer_segment
ORDER BY [Number of Customers] DESC;



--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM CustomerAnalysis
    GROUP BY category, item_purchased
)

SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders 
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
 select subscription_status,
 count(customer_id) as repeat_buyers
 from CustomerAnalysis
 where previous_purchases >5
 group by subscription_status


--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from CustomerAnalysis 
group by age_group
order by total_revenue desc;